# The boilerplate repository is set to private. Per GitHub documentation,
# self-hosted runners should not be used with public repos. However,
# I want the code to be available in a public repo.

name: Push to public repository
on: push
jobs:
  build:
    name: Pull boilerplates private and push boilerplates public
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all the branches.

      # Deploy keys lack workflow scope and will fail to push changes to workflows.
      # Changing dir name to still allow view of the workflow files
      - name: Change .github/workflows to github-examples/workflows
        run: |
          cd $GITHUB_WORKSPACE
          mv .github/ workflow-examples

      - name: Mirror to public repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:shellbender/boilerplates-public.git
          ssh_private_key:
            ${{ secrets.REPO_PRIVATE_KEY }}